# Generated by Django 5.1.7 on 2025-03-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('admission_number', models.CharField(max_length=50, unique=True)),
                ('register_number', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('dob', models.DateField()),
                ('age', models.IntegerField()),
                ('aadhar_number', models.CharField(max_length=12, unique=True)),
                ('mobile_number', models.CharField(max_length=12)),
                ('religion', models.CharField(max_length=50)),
                ('caste', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=50)),
                ('annual_income', models.DecimalField(decimal_places=2, max_digits=50)),
                ('course', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=10)),
                ('pincode', models.IntegerField()),
                ('district', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=50)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('father_name', models.CharField(max_length=100)),
                ('father_occupation', models.CharField(blank=True, max_length=100)),
                ('father_addresss', models.CharField(max_length=100)),
                ('father_mobile', models.CharField(max_length=15)),
                ('father_email', models.EmailField(max_length=50)),
                ('guardian_name', models.CharField(max_length=255)),
                ('guardian_addresss', models.CharField(max_length=100)),
                ('guardian_occupation', models.CharField(blank=True, max_length=255)),
                ('guardian_mobile', models.CharField(max_length=15)),
                ('guardian_email', models.EmailField(max_length=50)),
                ('ration_document', models.FileField(blank=True, null=True, upload_to='documents/ration/')),
                ('aadhar_document', models.FileField(blank=True, null=True, upload_to='documents/aadhar/')),
                ('income_certificate', models.FileField(blank=True, null=True, upload_to='documents/income/')),
                ('caste_documents', models.FileField(blank=True, null=True, upload_to='documents/caste/')),
            ],
        ),
    ]
