# Generated by Django 5.1.7 on 2025-03-20 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_student_mother_addresss_student_mother_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='student',
            name='course',
            field=models.CharField(choices=[('B.Tech', 'B.Tech'), ('PHD', 'PhD'), ('LET', 'Lateral Entry'), ('M.Tech', 'M.Tech')], max_length=20),
        ),
        migrations.AlterField(
            model_name='student',
            name='department',
            field=models.CharField(choices=[('Computer Science and Engineering', 'Computer Science and Engineering'), ('Electronics & Communication Engineering', 'Electronics & Communication Engineering'), ('Information Technology', 'Information Technology'), ('Electrical and Electronics Engineering', 'Electrical and Electronics Engineering'), ('Mechanical Engineering', 'Mechanical Engineering'), ('Civil Engineering', 'Civil Engineering')], max_length=50),
        ),
        migrations.AlterField(
            model_name='student',
            name='semester',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2'), ('S3', 'S3'), ('S4', 'S4'), ('S5', 'S5'), ('S6', 'S6'), ('S7', 'S7'), ('S8', 'S8'), ('Year 1', 'Year 1'), ('Year 2', 'Year 2'), ('Year 3', 'Year 3'), ('Year 4', 'Year 4'), ('Year 5', 'Year 5')], max_length=10),
        ),
    ]
