# Generated by Django 5.1.7 on 2025-03-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_student_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='register_number',
            new_name='username',
        ),
    ]
