# Generated by Django 5.1.7 on 2025-03-22 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_complaint_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Complaint',
        ),
    ]
