# Generated by Django 5.1.7 on 2025-03-29 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_messcommittee'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='messcommittee',
            unique_together={('month', 'year')},
        ),
        migrations.AddField(
            model_name='messcommittee',
            name='students',
            field=models.ManyToManyField(to='accounts.student'),
        ),
        migrations.RemoveField(
            model_name='messcommittee',
            name='student',
        ),
    ]
